# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  ddc-ui-pum = {
    pname = "ddc-ui-pum";
    version = "f7f334380e18af42297468b3cf696794bbfa2652";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddc-ui-pum";
      rev = "f7f334380e18af42297468b3cf696794bbfa2652";
      fetchSubmodules = false;
      sha256 = "sha256-kQ1fK65V0NtObqBy/FhcfACUGeI5Pk4t3Kw0BPpxChw=";
    };
    date = "2025-08-26";
  };
  ddc-vim = {
    pname = "ddc-vim";
    version = "ef527ad60b199b11d022a648a24ab6d424227943";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddc.vim";
      rev = "ef527ad60b199b11d022a648a24ab6d424227943";
      fetchSubmodules = false;
      sha256 = "sha256-Gp6xenZrXPl2UZ1W5yFvolWUW/rWzxGyVDY8lVcA0WA=";
    };
    date = "2025-11-16";
  };
  denops-vim = {
    pname = "denops-vim";
    version = "5cfca39988a36e42d81b925264fc846077a727e3";
    src = fetchFromGitHub {
      owner = "vim-denops";
      repo = "denops.vim";
      rev = "5cfca39988a36e42d81b925264fc846077a727e3";
      fetchSubmodules = false;
      sha256 = "sha256-4AACZ3h6uAqiXW24gUF1+uq7dnWA0w/PcxAeO4yxitc=";
    };
    date = "2025-10-26";
  };
  pum-vim = {
    pname = "pum-vim";
    version = "fed31b9f117e4c10332c30108152a935496bc3b5";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "pum.vim";
      rev = "fed31b9f117e4c10332c30108152a935496bc3b5";
      fetchSubmodules = false;
      sha256 = "sha256-hOUvq4hXlj7fxaJ/8ng3vEH2t0NrnWKuCqr7TwfD28c=";
    };
    date = "2025-11-10";
  };
  skk-dict = {
    pname = "skk-dict";
    version = "4eb91a3bbfef70bde940668ec60f3beae291e971";
    src = fetchFromGitHub {
      owner = "skk-dev";
      repo = "dict";
      rev = "4eb91a3bbfef70bde940668ec60f3beae291e971";
      fetchSubmodules = false;
      sha256 = "sha256-sWz85Q6Bu2WoKsckSp5SlcuPUQN2mcq+BHMqNXQ/aho=";
    };
    date = "2024-08-29";
  };
  skkeleton = {
    pname = "skkeleton";
    version = "71178b6debd9f1b3bb00abfd865ca642e82e24c7";
    src = fetchFromGitHub {
      owner = "vim-skk";
      repo = "skkeleton";
      rev = "71178b6debd9f1b3bb00abfd865ca642e82e24c7";
      fetchSubmodules = false;
      sha256 = "sha256-833WpBi0X6MhblLda1cp6dFU2zu+TYBgimlsBX+3rQo=";
    };
    date = "2025-10-27";
  };
  skkeleton-henkan-highlight = {
    pname = "skkeleton-henkan-highlight";
    version = "3f8d6d6d20a2397827138dbde7fa531bb487d849";
    src = fetchFromGitHub {
      owner = "NI57721";
      repo = "skkeleton-henkan-highlight";
      rev = "3f8d6d6d20a2397827138dbde7fa531bb487d849";
      fetchSubmodules = false;
      sha256 = "sha256-K5quESFM+5NZstbRgIIsfpXzBtnGJOQBF0SJiDi18jc=";
    };
    date = "2025-11-02";
  };
  skkeleton-state-popup = {
    pname = "skkeleton-state-popup";
    version = "2a72e33c47cc8762517d479c28f0deedde8b6794";
    src = fetchFromGitHub {
      owner = "NI57721";
      repo = "skkeleton-state-popup";
      rev = "2a72e33c47cc8762517d479c28f0deedde8b6794";
      fetchSubmodules = false;
      sha256 = "sha256-Zamd5GlFHpPrSiWVx3xK5EeUU8ZoEQf82yoBjQ7ypaM=";
    };
    date = "2025-11-05";
  };
}
