# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  ddc-ui-pum = {
    pname = "ddc-ui-pum";
    version = "f7f334380e18af42297468b3cf696794bbfa2652";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddc-ui-pum";
      rev = "f7f334380e18af42297468b3cf696794bbfa2652";
      fetchSubmodules = false;
      sha256 = "sha256-kQ1fK65V0NtObqBy/FhcfACUGeI5Pk4t3Kw0BPpxChw=";
    };
    date = "2025-08-26";
  };
  ddc-vim = {
    pname = "ddc-vim";
    version = "4f553b7f4e968971461820d05d3ff1601f9d7ab4";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddc.vim";
      rev = "4f553b7f4e968971461820d05d3ff1601f9d7ab4";
      fetchSubmodules = false;
      sha256 = "sha256-3WGlkMTesV60DEPdnTFVW1sLf3NaNK3tRM6C2EJm4pw=";
    };
    date = "2025-10-12";
  };
  denops-vim = {
    pname = "denops-vim";
    version = "a278b8342459e4687f24d4d575d72ff593326cee";
    src = fetchFromGitHub {
      owner = "vim-denops";
      repo = "denops.vim";
      rev = "a278b8342459e4687f24d4d575d72ff593326cee";
      fetchSubmodules = false;
      sha256 = "sha256-JIRV9xfOqX6GLqBAeYqOePqaFWSyAr157958hBxmP8w=";
    };
    date = "2025-08-24";
  };
  pum-vim = {
    pname = "pum-vim";
    version = "08734d52b03c354151dda3bb75a37a0ee39bbe7e";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "pum.vim";
      rev = "08734d52b03c354151dda3bb75a37a0ee39bbe7e";
      fetchSubmodules = false;
      sha256 = "sha256-WuSq5+0Tj0VgmdSYNxnswU1gNG2lSdoePNuVuiNkIOY=";
    };
    date = "2025-10-16";
  };
  skk-dict = {
    pname = "skk-dict";
    version = "4eb91a3bbfef70bde940668ec60f3beae291e971";
    src = fetchFromGitHub {
      owner = "skk-dev";
      repo = "dict";
      rev = "4eb91a3bbfef70bde940668ec60f3beae291e971";
      fetchSubmodules = false;
      sha256 = "sha256-sWz85Q6Bu2WoKsckSp5SlcuPUQN2mcq+BHMqNXQ/aho=";
    };
    date = "2024-08-29";
  };
  skkeleton = {
    pname = "skkeleton";
    version = "0c67893ffe0448666ec76283bc0a9685ac31fba9";
    src = fetchFromGitHub {
      owner = "vim-skk";
      repo = "skkeleton";
      rev = "0c67893ffe0448666ec76283bc0a9685ac31fba9";
      fetchSubmodules = false;
      sha256 = "sha256-6YRhQUANiYoSF5t4rV7kwU8essmUBNdejLumqR+tyTI=";
    };
    date = "2025-10-19";
  };
}
