# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  ddc-ui-pum = {
    pname = "ddc-ui-pum";
    version = "f7f334380e18af42297468b3cf696794bbfa2652";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddc-ui-pum";
      rev = "f7f334380e18af42297468b3cf696794bbfa2652";
      fetchSubmodules = false;
      sha256 = "sha256-kQ1fK65V0NtObqBy/FhcfACUGeI5Pk4t3Kw0BPpxChw=";
    };
    date = "2025-08-26";
  };
  ddc-vim = {
    pname = "ddc-vim";
    version = "b1eff146f035a3fb40ad41c7d69c7e09f89ba6b3";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddc.vim";
      rev = "b1eff146f035a3fb40ad41c7d69c7e09f89ba6b3";
      fetchSubmodules = false;
      sha256 = "sha256-RqngBulmngqQDSAyRR4QOJ0L7d3/Af0sMG1JcmRDsqA=";
    };
    date = "2026-04-05";
  };
  denops-vim = {
    pname = "denops-vim";
    version = "1df7a022d6e9cb3f6a3db43235e0f174ccd79e03";
    src = fetchFromGitHub {
      owner = "vim-denops";
      repo = "denops.vim";
      rev = "1df7a022d6e9cb3f6a3db43235e0f174ccd79e03";
      fetchSubmodules = false;
      sha256 = "sha256-lj8yjZrwE9GfNPDIpH4tCI4TTJHkYRlFFCTdqMqWtZg=";
    };
    date = "2026-03-22";
  };
  pum-vim = {
    pname = "pum-vim";
    version = "69aafe85ccbe001da3c709875e2af8051f8f421f";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "pum.vim";
      rev = "69aafe85ccbe001da3c709875e2af8051f8f421f";
      fetchSubmodules = false;
      sha256 = "sha256-wa1i0gqOUK3SAT5NVZypDSGAHX3kvybntX9C5I2zRm8=";
    };
    date = "2026-03-30";
  };
  skk-dict = {
    pname = "skk-dict";
    version = "0a164e6b990c5eb5b59eb7d8789f08865dc2f644";
    src = fetchFromGitHub {
      owner = "skk-dev";
      repo = "dict";
      rev = "0a164e6b990c5eb5b59eb7d8789f08865dc2f644";
      fetchSubmodules = false;
      sha256 = "sha256-xKMtHB54kVSwwwr+v248ewa7dwuavYVmc6KHrZwSdnM=";
    };
    date = "2026-04-12";
  };
  skkeleton = {
    pname = "skkeleton";
    version = "b530eac5a859ce2f8fa4d99fa5cd83b9d3199086";
    src = fetchFromGitHub {
      owner = "vim-skk";
      repo = "skkeleton";
      rev = "b530eac5a859ce2f8fa4d99fa5cd83b9d3199086";
      fetchSubmodules = false;
      sha256 = "sha256-OhHlG3ngNbvUSNqS/MFJpYI/cfbkxSxTPo8EiSwW/MU=";
    };
    date = "2026-04-02";
  };
  skkeleton-henkan-highlight = {
    pname = "skkeleton-henkan-highlight";
    version = "361ca90537e9cf7cd404899a4ed0bbef03124fd8";
    src = fetchFromGitHub {
      owner = "NI57721";
      repo = "skkeleton-henkan-highlight";
      rev = "361ca90537e9cf7cd404899a4ed0bbef03124fd8";
      fetchSubmodules = false;
      sha256 = "sha256-haDXPCyOkK4F0LMNR8yU+nL87hijwON1QpjmsJtv7gE=";
    };
    date = "2025-12-11";
  };
  skkeleton-state-popup = {
    pname = "skkeleton-state-popup";
    version = "e09dcbf85073df53c9c8d960f6160818572c1397";
    src = fetchFromGitHub {
      owner = "NI57721";
      repo = "skkeleton-state-popup";
      rev = "e09dcbf85073df53c9c8d960f6160818572c1397";
      fetchSubmodules = false;
      sha256 = "sha256-rUQ93m1jdopyFXH9KVmoTnNci8WsVz5472v+z115QoE=";
    };
    date = "2026-01-17";
  };
}
